package org.autojs.autojs

import org.autojs.autojs.model.script.Scripts.runWithBroadcastSender
import org.autojs.autojs.model.script.Scripts.openByOtherApps
import com.stardust.view.accessibility.AccessibilityService.Companion.disable
import com.stardust.notification.NotificationListenerService.Companion.instance
import com.stardust.app.isOpPermissionGranted
import org.autojs.autojs.model.script.Scripts.run
import org.autojs.autojs.model.script.Scripts.edit
import org.autojs.autojs.model.script.Scripts.runRepeatedly
import com.stardust.autojs.execution.ExecutionConfig.CREATOR.default
import org.autojs.autojs.model.script.Scripts.send
import com.stardust.view.accessibility.NodeInfo.boundsInScreen
import com.stardust.view.accessibility.NodeInfo.getChildren
import com.stardust.view.accessibility.NodeInfo.className
import com.stardust.view.accessibility.LayoutInspector.removeCaptureAvailableListener
import com.stardust.view.accessibility.LayoutInspector.addCaptureAvailableListener
import com.stardust.view.accessibility.LayoutInspector.captureCurrentWindow
import org.autojs.autojs.ui.floating.layoutinspector.NodeInfoView.setNodeInfo
import com.stardust.view.accessibility.AccessibilityService.Companion.instance
import com.stardust.autojs.core.activity.ActivityInfoProvider.getLatestPackageByUsageStatsIfGranted
import com.stardust.autojs.core.activity.ActivityInfoProvider.latestActivity
import org.autojs.autojs.model.script.Scripts.FILE_FILTER
import com.stardust.view.accessibility.AccessibilityServiceUtils.goToAccessibilitySetting
import com.stardust.view.accessibility.AccessibilityService.Companion.waitForEnabled
import com.stardust.view.accessibility.AccessibilityServiceUtils.isAccessibilityServiceEnabled
import com.stardust.view.accessibility.AccessibilityService.Companion.stickOnKeyObserver
import com.stardust.view.accessibility.OnKeyListener.Observer.addListener
import com.stardust.autojs.script.EncryptedScriptFileHeader.writeHeader
import com.stardust.util.AdvancedEncryptionStandard.encrypt
import com.stardust.autojs.execution.ExecutionConfig.delay
import com.stardust.autojs.execution.ExecutionConfig.loopTimes
import com.stardust.autojs.execution.ExecutionConfig.interval
import org.autojs.autojs.App.Companion.app
import org.autojs.autojs.App.dynamicBroadcastReceivers
import com.stardust.autojs.execution.ExecutionConfig.setArgument
import com.stardust.autojs.execution.ExecutionConfig.workingDirectory
import org.androidannotations.annotations.EFragment
import org.autojs.autojs.ui.main.ViewPagerFragment
import com.stardust.util.BackPressedHandler
import org.androidannotations.annotations.ViewById
import org.autojs.autojs.ui.widget.EWebView
import android.webkit.WebView
import android.os.Bundle
import org.greenrobot.eventbus.EventBus
import org.androidannotations.annotations.AfterViews
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout.OnRefreshListener
import org.autojs.autojs.ui.doc.DocsFragment
import com.google.android.material.floatingactionbutton.FloatingActionButton
import org.greenrobot.eventbus.Subscribe
import org.autojs.autojs.ui.main.QueryEvent
import butterknife.BindView
import android.widget.TextView
import org.autojs.autojs.ui.doc.ManualDialog
import butterknife.OnClick
import org.autojs.autojs.ui.doc.DocumentationActivity_
import org.autojs.autojs.ui.doc.DocumentationActivity
import butterknife.ButterKnife
import com.afollestad.materialdialogs.MaterialDialog
import android.graphics.drawable.ColorDrawable
import org.androidannotations.annotations.EActivity
import org.autojs.autojs.ui.BaseActivity
import com.stardust.autojs.core.console.ConsoleView
import com.stardust.autojs.core.console.ConsoleImpl
import org.androidannotations.annotations.Click
import android.widget.FrameLayout
import org.autojs.autojs.ui.widget.AutoAdapter
import org.autojs.autojs.ui.edit.debug.WatchingVariable
import org.autojs.autojs.ui.edit.debug.CodeEvaluator
import org.autojs.autojs.ui.widget.ViewHolderSupplier.ViewHolderCreator
import org.autojs.autojs.ui.widget.BindableViewHolder
import androidx.recyclerview.widget.RecyclerView
import androidx.recyclerview.widget.LinearLayoutManager
import org.autojs.autojs.ui.edit.debug.CodeEvaluateDialogBuilder
import org.autojs.autojs.theme.dialog.ThemeColorMaterialDialogBuilder
import androidx.recyclerview.widget.RecyclerView.AdapterDataObserver
import com.afollestad.materialdialogs.MaterialDialog.SingleButtonCallback
import com.afollestad.materialdialogs.DialogAction
import com.stardust.util.ClipboardUtil
import org.mozilla.javascript.ContextFactory
import org.autojs.autojs.ui.edit.debug.DebuggerSingleton
import android.widget.EditText
import android.content.SharedPreferences
import android.text.Editable
import android.preference.PreferenceManager
import org.autojs.autojs.model.editor.EditorTheme
import android.util.SparseIntArray
import org.autojs.autojs.ui.edit.theme.TokenMapping
import org.autojs.autojs.model.editor.TokenColor
import org.autojs.autojs.ui.edit.theme.Themes
import io.reactivex.subjects.PublishSubject
import io.reactivex.schedulers.Schedulers
import kotlin.jvm.Synchronized
import org.autojs.autojs.ui.edit.editor.CodeEditText
import android.text.TextWatcher
import org.autojs.autojs.ui.edit.editor.LayoutHelper
import org.autojs.autojs.ui.edit.editor.HVScrollView
import org.autojs.autojs.ui.edit.editor.TextViewUndoRedo
import org.autojs.autojs.ui.edit.editor.JavaScriptHighlighter
import com.stardust.autojs.script.JsBeautifier
import org.autojs.autojs.ui.edit.editor.AutoIndent
import com.google.android.material.snackbar.Snackbar
import org.autojs.autojs.ui.edit.editor.CodeEditor.CursorChangeCallback
import kotlin.Throws
import org.autojs.autojs.ui.edit.editor.CodeEditor.CheckedPatternSyntaxException
import org.autojs.autojs.ui.edit.editor.CodeEditor.BreakpointChangeListener
import kotlin.jvm.Volatile
import org.autojs.autojs.ui.edit.editor.JavaScriptHighlighter.HighlightTokens
import android.util.TimingLogger
import android.view.Gravity
import android.graphics.Typeface
import android.os.Build
import androidx.annotation.RequiresApi
import org.autojs.autojs.ui.edit.editor.BracketMatching
import android.os.Parcelable
import android.widget.TextViewHelper
import android.view.MotionEvent
import kotlin.jvm.JvmOverloads
import android.widget.Scroller
import android.view.VelocityTracker
import android.view.ViewGroup
import android.view.ViewConfiguration
import android.view.View.MeasureSpec
import android.view.FocusFinder
import android.view.ViewGroup.MarginLayoutParams
import android.view.ViewParent
import org.autojs.autojs.ui.edit.editor.TextViewUndoRedo.EditHistory
import org.autojs.autojs.ui.edit.editor.TextViewUndoRedo.EditTextChangeListener
import org.autojs.autojs.ui.edit.editor.TextViewUndoRedo.EditItem
import android.text.style.UnderlineSpan
import org.autojs.autojs.ui.widget.SimpleTextWatcher.AfterTextChangedListener
import org.autojs.autojs.ui.widget.SimpleTextWatcher
import android.view.View.OnLongClickListener
import org.autojs.autojs.ui.edit.toolbar.ToolbarFragment.OnMenuItemLongClickListener
import org.autojs.autojs.ui.edit.EditorView
import org.autojs.autojs.ui.edit.toolbar.ToolbarFragment
import com.stardust.autojs.rhino.debug.DebugCallback
import com.stardust.autojs.execution.ScriptExecution
import org.autojs.autojs.ui.edit.toolbar.DebugToolbarFragment
import org.autojs.autojs.ui.edit.editor.CodeEditor
import org.autojs.autojs.ui.edit.debug.DebugBar
import com.stardust.pio.PFiles
import com.stardust.autojs.runtime.exception.ScriptInterruptedException
import org.autojs.autojs.ui.edit.toolbar.SearchToolbarFragment
import org.autojs.autojs.ui.edit.keyboard.FunctionsKeyboardView.ClickCallback
import org.autojs.autojs.workground.WrapContentGridLayoutManger
import org.autojs.autojs.ui.edit.keyboard.FunctionsKeyboardView
import org.autojs.autojs.ui.edit.keyboard.FunctionsKeyboardView.PropertiesAdapter
import androidx.recyclerview.widget.GridLayoutManager.SpanSizeLookup
import android.graphics.drawable.Drawable
import org.autojs.autojs.ui.widget.GridDividerDecoration
import android.widget.LinearLayout
import org.autojs.autojs.ui.edit.keyboard.FunctionsKeyboardView.ModulesAdapter
import io.reactivex.android.schedulers.AndroidSchedulers
import org.autojs.autojs.ui.edit.keyboard.FunctionsKeyboardView.ModuleViewHolder
import android.view.LayoutInflater
import org.autojs.autojs.ui.edit.keyboard.FunctionsKeyboardView.PropertyViewHolder
import org.autojs.autojs.ui.edit.keyboard.FunctionsKeyboardHelper
import android.annotation.SuppressLint
import android.view.View.OnTouchListener
import android.view.WindowManager
import android.annotation.TargetApi
import android.util.DisplayMetrics
import org.autojs.autojs.model.autocomplete.CodeCompletions
import org.autojs.autojs.ui.edit.completion.CodeCompletionBar.OnHintClickListener
import android.os.Looper
import org.autojs.autojs.ui.edit.completion.CodeCompletionBar.CodeCompletionAdapter
import com.stardust.autojs.workground.WrapContentLinearLayoutManager
import org.autojs.autojs.ui.edit.ClassSearchDialogBuilder
import org.autojs.autojs.model.indices.ClassSearchingItem
import org.autojs.autojs.model.indices.ClassSearchingItem.ClassItem
import org.autojs.autojs.model.indices.AndroidClass
import org.autojs.autojs.model.indices.ClassSearchingItem.PackageItem
import com.stardust.autojs.script.JavaScriptSource
import com.stardust.util.IntentUtil
import org.autojs.autojs.ui.project.BuildActivity_
import org.autojs.autojs.ui.project.BuildActivity
import org.autojs.autojs.ui.edit.FindOrReplaceDialogBuilder
import org.autojs.autojs.ui.log.LogActivity_
import org.androidannotations.annotations.EViewGroup
import org.autojs.autojs.ui.edit.completion.CodeCompletionBar
import org.autojs.autojs.model.autocomplete.AutoCompletion
import android.content.BroadcastReceiver
import android.util.SparseBooleanArray
import org.autojs.autojs.ui.edit.toolbar.NormalToolbarFragment
import org.autojs.autojs.ui.edit.toolbar.NormalToolbarFragment_
import android.content.IntentFilter
import com.stardust.util.BackPressedHandler.HostActivity
import org.autojs.autojs.model.autocomplete.Symbols
import org.autojs.autojs.model.autocomplete.AutoCompletion.AutoCompleteCallback
import org.autojs.autojs.tool.Observers
import org.autojs.autojs.model.script.Scripts
import com.stardust.autojs.engine.JavaScriptEngine
import org.autojs.autojs.ui.edit.TextSizeSettingDialogBuilder
import org.autojs.autojs.ui.edit.TextSizeSettingDialogBuilder.PositiveCallback
import com.afollestad.materialdialogs.MaterialDialog.ListCallbackSingleChoice
import org.autojs.autojs.ui.edit.toolbar.SearchToolbarFragment_
import org.autojs.autojs.ui.edit.toolbar.DebugToolbarFragment_
import org.autojs.autojs.model.autocomplete.CodeCompletion
import com.stardust.app.OnActivityResultDelegate.DelegateHost
import com.stardust.autojs.core.permission.PermissionRequestProxyActivity
import com.stardust.app.OnActivityResultDelegate.Mediator
import org.autojs.autojs.ui.edit.EditorMenu
import com.stardust.autojs.core.permission.RequestPermissionCallbacks
import org.autojs.autojs.ui.edit.EditActivity
import org.autojs.autojs.ui.main.MainActivity_
import org.autojs.autojs.storage.file.TmpScriptFiles
import org.autojs.autojs.ui.edit.EditActivity_
import org.autojs.autojs.model.sample.SampleFile
import android.util.SparseArray
import org.autojs.autojs.ui.widget.ToolbarMenuItem
import com.stardust.theme.ThemeColorManager
import org.autojs.autojs.ui.common.ScriptOperations
import com.stardust.util.SparseArrayEntries
import org.autojs.autojs.ui.edit.ViewSampleActivity
import me.zhanghai.android.materialprogressbar.MaterialProgressBar
import org.autojs.autojs.model.indices.AndroidClassIndices
import android.widget.CheckBox
import butterknife.OnCheckedChanged
import butterknife.OnTextChanged
import android.widget.SeekBar.OnSeekBarChangeListener
import android.widget.SeekBar
import org.autojs.autojs.timing.TimedTask
import org.autojs.autojs.timing.IntentTask
import com.stardust.app.GlobalAppContext
import org.joda.time.format.DateTimeFormat
import org.autojs.autojs.ui.timing.TimedTaskSettingActivity
import org.autojs.autojs.timing.TimedTaskManager
import com.stardust.autojs.script.AutoFileSource
import org.autojs.autojs.ui.main.task.TaskGroup
import org.autojs.autojs.ui.main.task.Task.PendingTask
import org.autojs.autojs.ui.main.task.Task.RunningTask
import org.autojs.autojs.ui.main.task.TaskListRecyclerView
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout
import org.autojs.autojs.ui.widget.SimpleAdapterDataObserver
import androidx.recyclerview.widget.ThemeColorRecyclerView
import org.autojs.autojs.ui.main.task.TaskGroup.RunningTaskGroup
import org.autojs.autojs.ui.main.task.TaskGroup.PendingTaskGroup
import io.reactivex.disposables.Disposable
import com.stardust.autojs.execution.ScriptExecutionListener
import com.stardust.autojs.execution.SimpleScriptExecutionListener
import com.yqritc.recyclerviewflexibledivider.HorizontalDividerItemDecoration
import com.bignerdranch.expandablerecyclerview.ExpandableRecyclerAdapter
import org.autojs.autojs.ui.main.task.TaskListRecyclerView.TaskGroupViewHolder
import org.autojs.autojs.ui.main.task.TaskListRecyclerView.TaskViewHolder
import android.graphics.drawable.GradientDrawable
import org.autojs.autojs.ui.timing.TimedTaskSettingActivity_
import com.bignerdranch.expandablerecyclerview.ParentViewHolder
import org.autojs.autojs.ui.widget.AvatarView
import org.autojs.autojs.ui.main.drawer.DrawerMenuItem
import org.autojs.autojs.ui.main.drawer.DrawerMenuItemViewHolder
import org.autojs.autojs.ui.main.drawer.DrawerMenuAdapter
import org.autojs.autojs.ui.main.drawer.CommunityDrawerMenu
import org.autojs.autojs.ui.floating.FloatyWindowManger
import org.autojs.autojs.external.foreground.ForegroundService
import org.autojs.autojs.ui.main.drawer.DrawerMenuGroup
import org.autojs.autojs.ui.user.WebActivity_
import org.autojs.autojs.ui.user.WebActivity
import org.autojs.autojs.network.NodeBB
import org.autojs.autojs.ui.user.LoginActivity_
import android.app.AppOpsManager
import android.content.DialogInterface
import org.autojs.autojs.tool.WifiTool
import org.autojs.autojs.network.VersionService
import android.telephony.TelephonyManager
import android.content.pm.PackageManager
import org.autojs.autojs.ui.main.drawer.DrawerFragment
import org.autojs.autojs.tool.SimpleObserver
import org.autojs.autojs.ui.update.UpdateInfoDialogBuilder
import org.autojs.autojs.network.api.UserApi
import org.autojs.autojs.theme.ThemeColorManagerCompat
import org.autojs.autojs.ui.widget.BackgroundTarget
import org.autojs.autojs.ui.floating.CircularMenu
import org.autojs.autojs.ui.main.community.CommunityFragment.VisibilityChange
import org.greenrobot.eventbus.ThreadMode
import org.autojs.autojs.network.UserService.LoginStateChange
import org.autojs.autojs.ui.main.drawer.DrawerMenuGroupViewHolder
import io.reactivex.ObservableSource
import org.autojs.autojs.ui.main.community.CommunityFragment.LoadUrl
import org.autojs.autojs.ui.widget.PrefSwitch
import android.widget.CompoundButton
import android.webkit.JavascriptInterface
import com.stardust.autojs.script.StringScriptSource
import org.autojs.autojs.ui.main.FloatingActionMenu.OnFloatingActionButtonClickListener
import org.autojs.autojs.ui.explorer.ExplorerView
import org.autojs.autojs.ui.main.FloatingActionMenu
import org.autojs.autojs.ui.viewmodel.ExplorerItemList.SortConfig
import org.autojs.autojs.model.explorer.Explorers
import org.autojs.autojs.model.explorer.ExplorerDirPage
import org.autojs.autojs.model.explorer.ExplorerItem
import org.autojs.autojs.external.fileprovider.AppFileProvider
import org.autojs.autojs.ui.project.ProjectConfigActivity_
import org.autojs.autojs.ui.project.ProjectConfigActivity
import com.google.android.material.bottomsheet.BottomSheetDialog
import org.autojs.autojs.model.script.ScriptFile
import android.webkit.ValueCallback
import org.autojs.autojs.ui.filechooser.FileChooserDialogBuilder
import org.autojs.autojs.ui.filechooser.FileChooserDialogBuilder.SingleChoiceCallback
import com.stardust.pio.PFile
import org.autojs.autojs.ui.main.community.CommunityWebView
import org.autojs.autojs.ui.main.community.CommunityFragment
import androidx.viewpager.widget.ViewPager
import com.stardust.app.FragmentPagerAdapterBuilder.StoredFragmentPagerAdapter
import org.autojs.autojs.ui.update.VersionGuard
import org.autojs.autojs.ui.widget.SearchViewItem
import org.autojs.autojs.ui.main.MainActivity.DrawerOpenEvent
import org.autojs.autojs.ui.widget.CommonMarkdownView.DialogBuilder
import com.stardust.util.DrawerAutoClose
import com.stardust.util.BackPressedHandler.DoublePressExit
import com.google.android.material.tabs.TabLayout
import com.stardust.app.FragmentPagerAdapterBuilder
import org.autojs.autojs.ui.main.scripts.MyScriptListFragment_
import org.autojs.autojs.ui.doc.DocsFragment_
import org.autojs.autojs.ui.main.community.CommunityFragment_
import org.autojs.autojs.ui.main.market.MarketFragment_
import org.autojs.autojs.ui.main.task.TaskManagerFragment_
import com.stardust.app.FragmentPagerAdapterBuilder.OnFragmentInstantiateListener
import androidx.viewpager.widget.ViewPager.SimpleOnPageChangeListener
import org.autojs.autojs.ui.settings.SettingsActivity_
import com.stardust.enhancedfloaty.FloatyService
import com.stardust.util.DeveloperUtils
import org.autojs.autojs.ui.main.MainActivity
import org.autojs.autojs.ui.widget.SearchViewItem.QueryCallback
import androidx.annotation.CallSuper
import androidx.interpolator.view.animation.FastOutSlowInInterpolator
import androidx.annotation.AttrRes
import android.animation.AnimatorListenerAdapter
import okhttp3.ResponseBody
import org.autojs.autojs.ui.user.RegisterActivity_
import org.autojs.autojs.ui.error.ErrorReportActivity
import android.content.ClipData
import org.autojs.autojs.ui.error.AbstractIssueReporterActivity
import com.heinrichreimersoftware.androidissuereporter.model.github.GithubTarget
import androidx.annotation.StringDef
import android.widget.ImageButton
import com.github.aakira.expandablelayout.ExpandableRelativeLayout
import android.widget.RadioButton
import com.heinrichreimersoftware.androidissuereporter.model.DeviceInfo
import android.widget.TextView.OnEditorActionListener
import android.view.inputmethod.EditorInfo
import com.heinrichreimersoftware.androidissuereporter.model.github.GithubLogin
import com.google.android.material.textfield.TextInputLayout
import com.heinrichreimersoftware.androidissuereporter.model.github.ExtraInfo
import com.heinrichreimersoftware.androidissuereporter.model.Report
import org.eclipse.egit.github.core.client.GitHubClient
import org.eclipse.egit.github.core.Issue
import org.eclipse.egit.github.core.service.IssueService
import org.eclipse.egit.github.core.client.RequestException
import android.os.AsyncTask
import org.autojs.autojs.ui.common.RxDialogs
import org.autojs.autojs.ui.common.OptionListView
import org.autojs.autojs.ui.common.ScriptLoopDialog
import org.autojs.autojs.model.explorer.ExplorerPage
import org.autojs.autojs.model.explorer.Explorer
import org.autojs.autojs.model.explorer.ExplorerFileItem
import org.autojs.autojs.ui.shortcut.ShortcutCreateActivity
import org.autojs.autojs.external.ScriptIntents
import com.stardust.util.HashUtils
import com.stardust.app.OperationDialogBuilder
import android.widget.RadioGroup
import android.widget.TimePicker
import org.androidannotations.annotations.CheckedChange
import android.app.TimePickerDialog
import android.app.TimePickerDialog.OnTimeSetListener
import android.app.DatePickerDialog
import android.app.DatePickerDialog.OnDateSetListener
import android.widget.DatePicker
import com.stardust.autojs.execution.ExecutionConfig
import android.os.PowerManager
import android.content.ActivityNotFoundException
import org.autojs.autojs.external.receiver.DynamicBroadcastReceivers
import org.autojs.autojs.timing.TaskReceiver
import android.net.ConnectivityManager
import com.stardust.util.BiMap
import com.stardust.util.BiMaps
import org.autojs.autojs.ui.update.UpdateCheckDialog
import org.autojs.autojs.tool.IntentTool
import org.autojs.autojs.ui.widget.CommonMarkdownView
import com.stardust.app.OnActivityResultDelegate
import android.widget.ProgressBar
import android.webkit.WebSettings
import android.webkit.WebChromeClient
import android.webkit.WebChromeClient.FileChooserParams
import org.autojs.autojs.tool.ImageSelector
import org.autojs.autojs.tool.ImageSelector.ImageSelectorCallback
import android.webkit.WebViewClient
import android.graphics.Bitmap
import android.webkit.WebResourceRequest
import android.content.pm.ResolveInfo
import com.makeramen.roundedimageview.RoundedImageView
import android.content.SharedPreferences.OnSharedPreferenceChangeListener
import com.stardust.theme.ThemeColorMutable
import android.content.res.TypedArray
import com.stardust.theme.ThemeColor
import com.stardust.theme.ThemeColorHelper
import org.autojs.autojs.ui.widget.ViewHolderSupplier
import org.autojs.autojs.ui.widget.LevelBeamView
import android.app.SearchManager
import android.view.animation.Animation
import org.autojs.autojs.ui.widget.SlidingUpPanel
import android.widget.PopupWindow
import org.autojs.autojs.ui.widget.SimpleRecyclerViewAdapter
import org.autojs.autojs.ui.widget.BubblePopupMenu.MenuItemViewHolder
import org.autojs.autojs.ui.widget.SimpleRecyclerViewAdapter.ViewHolderFactory
import android.graphics.PorterDuff
import org.autojs.autojs.ui.widget.SimpleTextWatcher.BeforeTextChangedListener
import org.autojs.autojs.ui.widget.SimpleTextWatcher.OnTextChangedListener
import org.commonmark.renderer.html.HtmlRenderer
import org.commonmark.ext.heading.anchor.HeadingAnchorExtension
import org.autojs.autojs.ui.widget.CommonMarkdownView.OnPageFinishedListener
import androidx.recyclerview.widget.RecyclerView.ItemDecoration
import com.google.android.material.appbar.AppBarLayout
import android.view.ViewTreeObserver.OnGlobalLayoutListener
import android.util.TypedValue
import org.autojs.autojs.ui.widget.ExpandableRecyclerView.DefaultTitleAdapter.TitleViewHolder
import org.autojs.autojs.ui.widget.ScrollAwareFABBehavior
import android.animation.TimeInterpolator
import androidx.recyclerview.widget.ItemTouchHelper
import org.autojs.autojs.ui.widget.CheckBoxCompat
import androidx.cardview.widget.CardView
import com.stardust.autojs.project.ProjectConfig
import org.autojs.autojs.build.ApkKeyStore
import com.stardust.autojs.project.SigningConfig
import org.autojs.autojs.build.ApkSigner
import org.autojs.autojs.ui.shortcut.ShortcutIconSelectActivity_
import org.autojs.autojs.ui.project.SignManageActivity_
import org.autojs.autojs.autojs.build.ApkBuilder.AppConfig
import org.autojs.autojs.tool.BitmapTool
import org.autojs.autojs.build.ApkBuilderPluginHelper
import org.autojs.autojs.ui.shortcut.ShortcutIconSelectActivity
import org.autojs.autojs.ui.project.SignKeyCreateDialogBuilder
import org.autojs.autojs.ui.project.SignKeyCreateDialogBuilder.SignKeyCreatedCallback
import org.autojs.autojs.model.project.ProjectTemplate
import org.autojs.autojs.theme.widget.ThemeColorSwipeRefreshLayout
import org.autojs.autojs.ui.viewmodel.ExplorerItemList
import org.autojs.autojs.ui.explorer.ExplorerProjectToolbar
import org.autojs.autojs.ui.explorer.ExplorerView.ExplorerAdapter
import org.autojs.autojs.ui.explorer.ExplorerView.OnItemOperatedListener
import org.autojs.autojs.ui.explorer.ExplorerView.ExplorerPageState
import org.autojs.autojs.model.explorer.ExplorerProjectPage
import org.autojs.autojs.model.explorer.ExplorerChangeEvent
import org.autojs.autojs.ui.explorer.ExplorerView.CategoryViewHolder
import org.autojs.autojs.ui.explorer.ExplorerViewHelper
import org.autojs.autojs.model.explorer.ExplorerSampleItem
import org.autojs.autojs.model.explorer.ExplorerSamplePage
import com.stardust.autojs.project.ProjectLauncher
import com.stardust.enhancedfloaty.WindowBridge
import android.view.GestureDetector.SimpleOnGestureListener
import android.view.animation.BounceInterpolator
import org.autojs.autojs.ui.floating.gesture.BounceDragGesture
import android.animation.ValueAnimator
import android.animation.ValueAnimator.AnimatorUpdateListener
import org.autojs.autojs.ui.floating.layoutinspector.OnNodeInfoSelectListener
import org.autojs.autojs.ui.floating.layoutinspector.LayoutBoundsView
import com.stardust.util.ViewUtil
import pl.openrnd.multilevellistview.MultiLevelListView
import android.widget.AdapterView
import pl.openrnd.multilevellistview.NestType
import pl.openrnd.multilevellistview.MultiLevelListAdapter
import org.autojs.autojs.ui.floating.FullScreenFloatyWindow
import org.autojs.autojs.ui.widget.BubblePopupMenu
import org.autojs.autojs.ui.floating.layoutinspector.NodeInfoView
import org.autojs.autojs.ui.codegeneration.CodeGenerateDialog
import org.autojs.autojs.ui.floating.layoutinspector.LayoutHierarchyFloatyWindow
import com.stardust.view.accessibility.LayoutInspector
import com.stardust.view.accessibility.LayoutInspector.CaptureAvailableListener
import org.autojs.autojs.ui.floating.layoutinspector.LayoutBoundsFloatyWindow
import org.autojs.autojs.ui.floating.layoutinspector.LayoutHierarchyView
import org.autojs.autojs.ui.floating.CircularMenuWindow
import org.autojs.autojs.autojs.record.GlobalActionRecorder
import org.jdeferred.impl.DeferredObject
import org.autojs.autojs.ui.floating.CircularMenuFloaty
import org.autojs.autojs.ui.floating.CircularActionMenu
import org.autojs.autojs.tool.RootTool
import com.stardust.enhancedfloaty.FloatyWindow
import org.jdeferred.DoneCallback
import org.jdeferred.FailCallback
import org.autojs.autojs.ui.floating.CircularActionMenu.OnStateChangeListener
import android.graphics.PointF
import android.view.animation.ScaleAnimation
import org.autojs.autojs.ui.floating.OrientationAwareWindowBridge
import android.view.OrientationEventListener
import com.stardust.util.ScreenMetrics
import com.stardust.enhancedfloaty.WindowBridge.DefaultImpl
import org.autojs.autojs.ui.floating.CircularActionMenu.OnStateChangeListenerAdapter
import com.stardust.autojs.util.FloatingPermission
import android.graphics.PixelFormat
import android.view.SurfaceView
import android.view.SurfaceHolder
import org.autojs.autojs.ui.settings.TestSurfaceView
import com.stardust.theme.preference.ThemeColorPreferenceFragment
import org.autojs.autojs.ui.settings.AboutActivity_
import android.preference.Preference
import de.psdev.licensesdialog.LicenseResolver
import org.autojs.autojs.ui.settings.SettingsActivity.PreferenceFragment.MozillaPublicLicense20
import de.psdev.licensesdialog.LicensesDialog
import de.psdev.licensesdialog.licenses.License
import com.stardust.theme.app.ColorSelectActivity.ColorItem
import com.stardust.theme.app.ColorSelectActivity
import com.afollestad.materialdialogs.prefs.MaterialEditTextPreference
import org.autojs.autojs.storage.file.FileObservable
import org.autojs.autojs.external.shortcut.Shortcut
import org.autojs.autojs.external.shortcut.ShortcutActivity
import android.os.PersistableBundle
import android.graphics.BitmapFactory
import org.autojs.autojs.ui.shortcut.ShortcutIconSelectActivity.AppItem
import org.autojs.autojs.ui.shortcut.ShortcutIconSelectActivity.AppsAdapter
import android.content.pm.ApplicationInfo
import org.autojs.autojs.ui.shortcut.ShortcutIconSelectActivity.AppIconViewHolder
import org.autojs.autojs.model.explorer.ExplorerSorter
import androidx.recyclerview.widget.SimpleItemAnimator
import org.autojs.autojs.ui.filechooser.FileChooseListView
import org.autojs.autojs.ui.filechooser.FileChooserDialogBuilder.MultiChoiceCallback
import org.autojs.autojs.model.explorer.ExplorerFileProvider
import org.autojs.autojs.ui.codegeneration.CodeGenerateDialog.OptionGroupViewHolder
import org.autojs.autojs.ui.codegeneration.CodeGenerateDialog.OptionViewHolder
import com.stericson.RootShell.RootShell
import com.stardust.autojs.core.util.ProcessShell
import android.net.wifi.WifiManager
import android.net.DhcpInfo
import com.google.gson.JsonElement
import com.google.gson.JsonArray
import android.graphics.drawable.BitmapDrawable
import com.google.gson.JsonObject
import com.google.gson.JsonPrimitive
import com.google.gson.JsonNull
import org.autojs.autojs.tool.SafeJsonObject
import org.autojs.autojs.tool.MaterialDialogFactory
import com.stardust.view.accessibility.AccessibilityServiceUtils
import org.autojs.autojs.build.apksigner.zipio.ZipInput
import org.autojs.autojs.build.apksigner.zipio.ZioEntryOutputStream
import org.autojs.autojs.build.apksigner.zipio.ZipOutput
import org.autojs.autojs.build.apksigner.zipio.ZioEntry
import org.autojs.autojs.build.apksigner.zipio.ZioEntryInputStream
import org.autojs.autojs.build.apksigner.zipio.CentralEnd
import org.autojs.autojs.build.apksigner.LoadKeystoreException
import org.spongycastle.util.encoders.Base64Encoder
import org.autojs.autojs.build.apksigner.ZipSigner
import org.autojs.autojs.build.apksigner.SignatureBlockGenerator
import org.autojs.autojs.build.apksigner.KeyStoreFileManager
import org.autojs.autojs.build.apksigner.CertCreator.DistinguishedNameValues
import org.autojs.autojs.build.apksigner.CertCreator
import org.spongycastle.x509.X509V3CertificateGenerator
import org.spongycastle.jce.X509Principal
import org.spongycastle.asn1.ASN1ObjectIdentifier
import org.spongycastle.asn1.x500.style.BCStyle
import org.spongycastle.jce.provider.BouncyCastleProvider
import org.autojs.autojs.build.apksigner.KeyStoreFileManager.JksKeyStore
import org.spongycastle.cms.CMSTypedData
import org.spongycastle.cms.CMSProcessableByteArray
import org.spongycastle.cert.jcajce.JcaCertStore
import org.spongycastle.cms.CMSSignedDataGenerator
import org.spongycastle.operator.jcajce.JcaContentSignerBuilder
import org.spongycastle.operator.jcajce.JcaDigestCalculatorProviderBuilder
import org.spongycastle.operator.DigestCalculatorProvider
import org.spongycastle.cms.jcajce.JcaSignerInfoGeneratorBuilder
import org.spongycastle.cms.SignerInfoGenerator
import org.spongycastle.cms.CMSSignedData
import com.google.gson.annotations.SerializedName
import org.autojs.autojs.model.editor.TokenColorSettings
import com.google.gson.Gson
import com.google.gson.GsonBuilder
import org.autojs.autojs.model.editor.TokenColorDeserializer
import org.autojs.autojs.model.editor.EditorColors
import com.google.gson.JsonDeserializer
import com.google.gson.JsonParseException
import com.google.gson.JsonDeserializationContext
import android.content.res.AssetManager
import com.stardust.autojs.script.ScriptSource
import com.stardust.autojs.script.JavaScriptFileSource
import org.autojs.autojs.model.script.PathChecker
import android.Manifest.permission
import com.google.gson.reflect.TypeToken
import org.autojs.autojs.model.indices.AndroidClassIndices.LoadException
import org.autojs.autojs.model.explorer.ExplorerProvider
import org.autojs.autojs.model.explorer.WorkspaceFileProvider
import org.autojs.autojs.model.autocomplete.DictionaryTree
import org.autojs.autojs.model.autocomplete.AnyWordsCompletion
import com.stardust.autojs.core.inputevent.ShellKeyObserver
import org.autojs.autojs.autojs.key.GlobalKeyObserver.OnVolumeDownListener
import com.stardust.autojs.core.inputevent.InputEventObserver
import com.stardust.autojs.apkbuilder.ApkPackager
import com.stardust.autojs.apkbuilder.ManifestEditor
import com.stardust.autojs.script.EncryptedScriptFileHeader
import com.stardust.util.AdvancedEncryptionStandard
import org.autojs.autojs.autojs.build.ApkBuilder.ManifestEditorWithAuthorities
import com.stardust.autojs.project.BuildInfo
import zhao.arsceditor.ResDecoder.ARSCDecoder
import zhao.arsceditor.ResDecoder.data.ResTable
import zhao.arsceditor.ArscUtil
import pxb.android.axml.AxmlWriter
import pxb.android.StringItem
import com.stardust.autojs.core.record.inputevent.TouchRecorder
import com.stardust.autojs.core.record.inputevent.InputEventRecorder
import com.stardust.autojs.core.record.inputevent.InputEventToAutoFileRecorder
import com.stardust.autojs.core.record.inputevent.InputEventToRootAutomatorRecorder
import com.afollestad.materialdialogs.MaterialDialog.ListCallback
import org.autojs.autojs.autojs.AutoJs.LayoutInspectFloatyWindow
import com.stardust.autojs.core.console.GlobalConsole
import com.stardust.autojs.runtime.accessibility.AccessibilityConfig
import androidx.localbroadcastmanager.content.LocalBroadcastManager
import org.autojs.autojs.storage.database.BaseModel
import android.app.PendingIntent
import org.joda.time.DateTimeConstants
import android.content.IntentFilter.MalformedMimeTypeException
import org.autojs.autojs.storage.database.TimedTaskDatabase
import org.autojs.autojs.storage.database.IntentTaskDatabase
import org.autojs.autojs.timing.TimedTaskScheduler
import io.reactivex.Flowable
import com.evernote.android.job.JobRequest
import com.evernote.android.job.JobManager
import com.evernote.android.job.JobCreator
import org.autojs.autojs.timing.TimedTaskScheduler.CheckTasksJob
import org.autojs.autojs.timing.TimedTaskScheduler.TimedTaskJob
import retrofit2.http.GET
import retrofit2.http.FormUrlEncoded
import retrofit2.http.POST
import org.autojs.autojs.network.entity.notification.NotificationResponse
import retrofit2.http.Streaming
import retrofit2.http.Url
import okhttp3.CookieJar
import okhttp3.HttpUrl
import okhttp3.Cookie
import org.autojs.autojs.network.util.WebkitCookieManagerProxy
import org.autojs.autojs.network.entity.user.GroupsItem
import org.autojs.autojs.network.entity.topic.Replies
import org.autojs.autojs.network.entity.topic.Post
import org.autojs.autojs.network.entity.topic.AppInfo
import android.text.Html
import org.autojs.autojs.network.entity.topic.Topic
import org.autojs.autojs.network.entity.topic.Pagination
import org.autojs.autojs.network.entity.topic.Privileges
import org.autojs.autojs.network.entity.config.Cookies
import org.autojs.autojs.network.entity.config.Markdown
import retrofit2.Retrofit
import org.autojs.autojs.network.api.DownloadApi
import com.stardust.concurrent.VolatileBox
import org.autojs.autojs.network.download.DownloadManager.DownloadTask
import com.jakewharton.retrofit2.adapter.rxjava2.RxJava2CallAdapterFactory
import okhttp3.OkHttpClient
import okhttp3.Interceptor
import org.autojs.autojs.network.api.ConfigApi
import retrofit2.converter.gson.GsonConverterFactory
import com.jakewharton.retrofit2.adapter.kotlin.coroutines.CoroutineCallAdapterFactory
import org.autojs.autojs.network.api.UpdateCheckApi
import android.database.sqlite.SQLiteOpenHelper
import android.database.sqlite.SQLiteDatabase
import android.content.ContentValues
import org.autojs.autojs.storage.database.Database.CursorIterator
import android.content.ContentResolver
import org.autojs.autojs.external.open.EditIntentActivity
import org.autojs.autojs.external.tile.LayoutInspectTileService
import android.service.quicksettings.TileService
import com.twofortyfouram.locale.sdk.client.receiver.AbstractPluginSettingReceiver
import org.autojs.autojs.external.open.RunIntentActivity
import com.twofortyfouram.locale.sdk.client.ui.activity.AbstractAppCompatPluginActivity
import org.autojs.autojs.external.tasker.TaskerScriptEditActivity
import org.autojs.autojs.external.tasker.TaskerScriptEditActivity_
import android.appwidget.AppWidgetProvider
import android.appwidget.AppWidgetManager
import org.autojs.autojs.external.widget.ScriptWidget
import org.autojs.autojs.external.widget.ScriptWidgets
import android.widget.RemoteViews
import org.autojs.autojs.external.receiver.BaseBroadcastReceiver
import org.autojs.autojs.external.receiver.DynamicBroadcastReceivers.ReceiverRegistry
import org.autojs.autojs.external.receiver.StaticBroadcastReceiver
import android.content.Intent.ShortcutIconResource
import android.content.pm.ShortcutInfo
import android.os.IBinder
import android.app.NotificationManager
import android.app.NotificationChannel
import com.stardust.autojs.script.SequenceScriptSource
import android.app.IntentService
import androidx.recyclerview.widget.GridLayoutManager
import androidx.recyclerview.widget.RecyclerView.Recycler
import okhttp3.WebSocketListener
import okio.ByteString
import androidx.annotation.AnyThread
import androidx.annotation.MainThread
import com.stardust.io.Zip
import android.view.accessibility.AccessibilityEvent
import org.autojs.autojs.accessibility.AccessibilityEventHelper
import org.junit.Test
import java.util.regex.Pattern

/**
 * Example local unit test, which will execute on the development machine (host).
 *
 * @see [Testing documentation](http://d.android.com/tools/testing)
 */
class ExampleUnitTest {
    @Test
    fun test() {
        val matcher = Pattern.compile("[0-9]+").matcher("2937Finish!")
        if (matcher.find()) {
            println(matcher.group())
        }
    }

    @Test
    fun testAutoReorder() {
    }
}